### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by bestgopher** [j4ng5y/zed_golangci_lint#1]
Hi, I installed the extension.But I don't know how to use it.Could you give me some help?

**Comment by j4ng5y** [comment]
what would you expect to happen? that might help me frame my response :D

**Comment by bestgopher** [comment]
I installed the extension. Then I don't know whether it works fine.

**Comment by j4ng5y** [comment]
So, when you are working on a normal "*.go" file, if you are experiencing linting issues, it should be injecting LSP messages into the workspace. I'll make sure that nothing is broken on my end as well from when I pushed this version.

**Comment by bestgopher** [comment]
> Then I don't know whether it works fine.

I want to know what will happen if it works.

**Comment by bdeb1337** [comment]
+1 just installed this plugin, and nothing seems to happen. Edited an open "*.go" file that had no issues, introduced an issue, saved, and nothing was to be found anywhere.

**Comment by bestgopher** [comment]
> +1 just installed this plugin, and nothing seems to happen. Edited an open "*.go" file that had no issues, introduced an issue, saved, and nothing was to be found anywhere.

+1

**Comment by psapezhka** [comment]
Fixed in #3 and #6

**Comment by bestgopher** [comment]
> Fixed in #3 and #6

LGTM

**Comment by vigo** [comment]
can anyone tell us how da hell we use this? nothing happens... from extenstions i installed it and nothing happens... do we need to add some config to settings?

**Comment by paveldroo** [comment]
same here, when I uncomment //nolint comments for testing - nothing happens

**Comment by bek-shoyatbek** [comment]
+1

**Comment by bestgopher** [comment]
Hi, everyone. I’m closing this issue because I’ve decided to stop using this extension.
